# Lefthook configuration for git hooks
# Install hooks with: lefthook install

pre-commit:
  parallel: true
  commands:
    fmt:
      glob: "*.go"
      run: |
        files=$(gofmt -l {staged_files})
        if [ -n "$files" ]; then
          echo "Not formatted:"
          echo "$files"
          exit 1
        fi

    vet:
      glob: "*.go"
      run: go vet ./...

    lint:
      glob: "*.go"
      run: |
        if ! command -v golangci-lint >/dev/null 2>&1; then
          echo "ERROR: golangci-lint not installed"
          echo "Install with: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
          exit 1
        fi
        golangci-lint run ./...

pre-push:
  commands:
    test:
      run: go test -race -short ./...
